wordpress:
  build: .
  ports:
    - 8888:80
  links:
    - db:mysql
  volumes:
    - ./wordpress:/var/www/html
  dns: 208.67.222.222
  environment:
    WP_VERSION: 4.9.7
    WP_URL: http://localhost:8888

db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: password
